export function exportChatAsPdf(messages: any[], roomName: string) {
  const styles = `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Courier New', monospace;
      background: #0a0a0f;
      color: #e0e0e0;
      padding: 40px;
    }
    .header {
      border-bottom: 1px solid #00e5ff40;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #00e5ff;
      font-size: 18px;
      text-transform: uppercase;
      letter-spacing: 4px;
      font-weight: 700;
    }
    .header .meta {
      color: #666;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 2px;
      margin-top: 8px;
    }
    .messages { display: flex; flex-direction: column; gap: 16px; }
    .message {
      border: 1px solid #1a1a2e;
      padding: 12px 16px;
      background: #0d0d1a;
    }
    .message.self { border-color: #00e5ff20; background: #00e5ff08; }
    .msg-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }
    .sender {
      color: #00e5ff;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 2px;
    }
    .time {
      color: #555;
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .content {
      color: #ccc;
      font-size: 13px;
      line-height: 1.5;
      white-space: pre-wrap;
    }
    .footer {
      border-top: 1px solid #00e5ff40;
      padding-top: 20px;
      margin-top: 30px;
      text-align: center;
      color: #444;
      font-size: 8px;
      text-transform: uppercase;
      letter-spacing: 3px;
    }
  `;

  const messagesHtml = messages.map(m => {
    const time = new Date(m.timestamp).toLocaleString();
    const self = m.isSelf ? 'self' : '';
    return `
      <div class="message ${self}">
        <div class="msg-header">
          <span class="sender">${escapeHtml(m.senderName || 'Unknown')}</span>
          <span class="time">${time}</span>
        </div>
        <div class="content">${escapeHtml(m.content || '')}</div>
      </div>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${escapeHtml(roomName)} - Chat Export</title><style>${styles}</style></head>
<body>
  <div class="header">
    <h1>${escapeHtml(roomName)}</h1>
    <div class="meta">Exported ${new Date().toLocaleString()} &middot; ${messages.length} messages</div>
  </div>
  <div class="messages">${messagesHtml}</div>
  <div class="footer">Generated by Terminal Chat &middot; End-to-End Encrypted</div>
  <script>window.print()<\/script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, '_blank');
  if (w) {
    w.onafterprint = () => { URL.revokeObjectURL(url); };
    setTimeout(() => { URL.revokeObjectURL(url); }, 60000);
  }
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
